export interface MusicAlbum {
  artist: string;
  title: string;
  src: string;
  credit: string;
  source: string;
  licenseVersion: `3.0` | `4.0`;
  permissionTicket: string;
  catalogUrl: string;
}

export const musicArtwork = {
  'the-seasons': {
    artist: `Ben Wendel`,
    title: `The Seasons`,
    src: `/music/licensed-artwork/the-seasons.webp`,
    credit: `Ben Wendel`,
    source: `https://commons.wikimedia.org/wiki/File:The_Seasons_Ben_Wendel_Album_Cover.jpg`,
    licenseVersion: `4.0`,
    permissionTicket: `2023092910007451`,
    catalogUrl: `https://music.apple.com/us/album/the-seasons/1421358636`,
  },
  'all-one': {
    artist: `Ben Wendel`,
    title: `All One`,
    src: `/music/licensed-artwork/all-one.webp`,
    credit: `Ben Wendel`,
    source: `https://commons.wikimedia.org/wiki/File:All_One_Ben_Wendel_Album_Cover.jpg`,
    licenseVersion: `4.0`,
    permissionTicket: `2023092910007451`,
    catalogUrl: `https://music.apple.com/us/album/all-one/1667562136`,
  },
  'high-heart': {
    artist: `Ben Wendel`,
    title: `High Heart`,
    src: `/music/licensed-artwork/high-heart.webp`,
    credit: `Ben Wendel`,
    source: `https://commons.wikimedia.org/wiki/File:High_Heart_Ben_Wendel_Album_Cover.jpg`,
    licenseVersion: `4.0`,
    permissionTicket: `2023092910007451`,
    catalogUrl: `https://music.apple.com/us/album/high-heart/1527425008`,
  },
  capsule: {
    artist: `The Brian Landrus Kaleidoscope`,
    title: `Capsule`,
    src: `/music/licensed-artwork/capsule.webp`,
    credit: `Brian Landrus`,
    source: `https://commons.wikimedia.org/wiki/File:Landrus_Kaleidoscope_Capsule_Cover.JPG`,
    licenseVersion: `3.0`,
    permissionTicket: `2013032610005943`,
    catalogUrl: `https://music.apple.com/us/album/capsule/431127515`,
  },
  mirage: {
    artist: `Brian Landrus Kaleidoscope`,
    title: `Mirage`,
    src: `/music/licensed-artwork/mirage.webp`,
    credit: `Brian Landrus`,
    source: `https://commons.wikimedia.org/wiki/File:Brian_Landrus_Kaleidoscope_Mirage_Cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2013032610005907`,
    catalogUrl: `https://music.apple.com/us/album/mirage/645779740`,
  },
  'blu-escape': {
    artist: `Hank Hehmsoth`,
    title: `Blu-Escape`,
    src: `/music/licensed-artwork/blu-escape.webp`,
    credit: `Hank Hehmsoth / Time Space Fabrics`,
    source: `https://commons.wikimedia.org/wiki/File:Blu-Escape-Album-Cover-Hank-Hehmsoth-2024.webp`,
    licenseVersion: `4.0`,
    permissionTicket: `2026041810002686`,
    catalogUrl: `https://music.apple.com/us/album/blu-escape/1733862884`,
  },
  europa: {
    artist: `Ron Korb`,
    title: `Europa`,
    src: `/music/licensed-artwork/europa.webp`,
    credit: `Hsiao-Tsui Yeh and Ron Korb`,
    source: `https://commons.wikimedia.org/wiki/File:Ron_Korb_Album_Europa.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2013032610001018`,
    catalogUrl: `https://music.apple.com/us/album/europa/909177778`,
  },
  dinas: {
    artist: `Calan`,
    title: `Dinas`,
    src: `/music/licensed-artwork/dinas.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Dinas,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/dinas/994599515`,
  },
  hyn: {
    artist: `Carreg Lafar`,
    title: `Hyn`,
    src: `/music/licensed-artwork/hyn.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Hyn,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/hyn/163957367`,
  },
  profiad: {
    artist: `Carreg Lafar`,
    title: `Profiad`,
    src: `/music/licensed-artwork/profiad.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Profiad,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/profiad-experience/158222416`,
  },
  'ysbryd-y-werin': {
    artist: `Carreg Lafar`,
    title: `Ysbryd y Werin`,
    src: `/music/licensed-artwork/ysbryd-y-werin.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Ysbryd_Y_Werin,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/ysbryd-y-werin/191934283`,
  },
  crasdant: {
    artist: `Crasdant`,
    title: `Crasdant`,
    src: `/music/licensed-artwork/crasdant.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Crasdant,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/crasdant/164120620`,
  },
  dwndwr: {
    artist: `Crasdant`,
    title: `Dwndwr`,
    src: `/music/licensed-artwork/dwndwr.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Dwndwr_-_The_Great_Noise,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/dwndwr-the-great-noise/155726301`,
  },
  'nos-sadwrn-bach': {
    artist: `Crasdant`,
    title: `Nos Sadwrn Bach`,
    src: `/music/licensed-artwork/nos-sadwrn-bach.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Nos_Sadwrn_Bach_-_Not_Yet_Saturday,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/nos-sadwrn-bach-not-yet-saturday/158221599`,
  },
  'ar-y-ffin': {
    artist: `Delyth Jenkins`,
    title: `Ar y Ffin`,
    src: `/music/licensed-artwork/ar-y-ffin.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Ar_Y_Ffin,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/ar-y-ffin/160153627`,
  },
  'hen-aelwyd': {
    artist: `Robin Huw Bowen`,
    title: `Hen Aelwyd`,
    src: `/music/licensed-artwork/hen-aelwyd.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Hen_Aelwyd_-_Old_Hearth,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/hen-alwyd-old-hearth/159039563`,
  },
  'iaith-enaid': {
    artist: `Robin Huw Bowen`,
    title: `Iaith Enaid`,
    src: `/music/licensed-artwork/iaith-enaid.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Iaith_Enaid_-_The_Language_Of_The_Soul,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/iaith-enaid-the-language-of-the-soul/970562651`,
  },
  'y-ffordd-i-aberystwyth': {
    artist: `Robin Huw Bowen`,
    title: `Y Ffordd i Aberystwyth`,
    src: `/music/licensed-artwork/y-ffordd-i-aberystwyth.webp`,
    credit: `Sain (Recordiau) Cyf.`,
    source: `https://commons.wikimedia.org/wiki/File:Y_Ffordd_I_Aberystwyth_-_The_Road_To_Aberystwyth,_album_cover.jpg`,
    licenseVersion: `3.0`,
    permissionTicket: `2017050910011681`,
    catalogUrl: `https://music.apple.com/us/album/y-ffordd-i-aberystwyth/217921660`,
  },
} as const satisfies Record<string, MusicAlbum>;

export type MusicAlbumId = keyof typeof musicArtwork;

export const chosenAlbumIds = [
  `the-seasons`,
  `dinas`,
  `capsule`,
  `hyn`,
  `europa`,
  `iaith-enaid`,
] as const satisfies readonly MusicAlbumId[];

export const musicMarqueeIds = [
  [
    `crasdant`,
    `the-seasons`,
    `ar-y-ffin`,
    `blu-escape`,
    `hen-aelwyd`,
    `capsule`,
    `profiad`,
    `nos-sadwrn-bach`,
  ],
  [
    `dinas`,
    `mirage`,
    `ysbryd-y-werin`,
    `y-ffordd-i-aberystwyth`,
    `hyn`,
    `all-one`,
    `dwndwr`,
    `ar-y-ffin`,
  ],
  [
    `profiad`,
    `high-heart`,
    `europa`,
    `crasdant`,
    `blu-escape`,
    `hen-aelwyd`,
    `mirage`,
    `ysbryd-y-werin`,
  ],
  [
    `dwndwr`,
    `iaith-enaid`,
    `all-one`,
    `nos-sadwrn-bach`,
    `ar-y-ffin`,
    `y-ffordd-i-aberystwyth`,
    `high-heart`,
  ],
] as const satisfies readonly (readonly MusicAlbumId[])[];
