import '../watch-helpers.just'

_default:
  @just --choose

gen:
  @xcodegen -s project.yml
  @xml-lint --fix app/Info.plist

xcode:
  @just gen
  @open GertrudeMusic.xcodeproj

build-views:
  @cd lib-views && swift build

build-tca:
  @cd lib-tca && swift build

build:
  @just build-views
  @just build-tca

build-app:
  @xcodebuild -project GertrudeMusic.xcodeproj -scheme 'Gertrude Music' -configuration Debug -destination 'generic/platform=iOS Simulator' build

test:
  @cd lib-views && SWIFT_DETERMINISTIC_HASHING=1 swift test
  @cd lib-tca && SWIFT_DETERMINISTIC_HASHING=1 swift test

fix:
  @swiftformat --exclude '**/.build' .
  @xml-lint --fix app/Info.plist

clean:
  @rm -rf lib-views/.build lib-tca/.build
  @find lib-views lib-tca -type f \( -name '*.o' -o -name '*.d' -o -name '*.swiftdeps' -o -name '*.swiftdeps~' \) -delete
