/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSignoutRouteImport } from './routes/_app/signout'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as unauthedLoginRouteImport } from './routes/(unauthed)/login'
import { Route as AppActivityIndexRouteImport } from './routes/_app/activity/index'
import { Route as AppRequestsUnlockRouteImport } from './routes/_app/requests/unlock'
import { Route as AppRequestsSuspensionRouteImport } from './routes/_app/requests/suspension'
import { Route as unauthedOtpTokenRouteImport } from './routes/(unauthed)/otp/$token'
import { Route as AppRequestsSuspensionRequestIdRouteImport } from './routes/_app/requests/suspension/$requestId'
import { Route as AppActivityDayDayRouteImport } from './routes/_app/activity/day/$day'
import { Route as AppActivityPersonPersonIdIndexRouteImport } from './routes/_app/activity/person/$personId/index'
import { Route as AppActivityPersonPersonIdDayDayRouteImport } from './routes/_app/activity/person/$personId/day/$day'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignoutRoute = AppSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const unauthedLoginRoute = unauthedLoginRouteImport.update({
  id: '/(unauthed)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityIndexRoute = AppActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequestsUnlockRoute = AppRequestsUnlockRouteImport.update({
  id: '/requests/unlock',
  path: '/requests/unlock',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequestsSuspensionRoute = AppRequestsSuspensionRouteImport.update({
  id: '/requests/suspension',
  path: '/requests/suspension',
  getParentRoute: () => AppRouteRoute,
} as any)
const unauthedOtpTokenRoute = unauthedOtpTokenRouteImport.update({
  id: '/(unauthed)/otp/$token',
  path: '/otp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRequestsSuspensionRequestIdRoute =
  AppRequestsSuspensionRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => AppRequestsSuspensionRoute,
  } as any)
const AppActivityDayDayRoute = AppActivityDayDayRouteImport.update({
  id: '/activity/day/$day',
  path: '/activity/day/$day',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityPersonPersonIdIndexRoute =
  AppActivityPersonPersonIdIndexRouteImport.update({
    id: '/activity/person/$personId/',
    path: '/activity/person/$personId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppActivityPersonPersonIdDayDayRoute =
  AppActivityPersonPersonIdDayDayRouteImport.update({
    id: '/activity/person/$personId/day/$day',
    path: '/activity/person/$personId/day/$day',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof unauthedLoginRoute
  '/people': typeof AppPeopleRoute
  '/signout': typeof AppSignoutRoute
  '/otp/$token': typeof unauthedOtpTokenRoute
  '/requests/suspension': typeof AppRequestsSuspensionRouteWithChildren
  '/requests/unlock': typeof AppRequestsUnlockRoute
  '/activity/': typeof AppActivityIndexRoute
  '/activity/day/$day': typeof AppActivityDayDayRoute
  '/requests/suspension/$requestId': typeof AppRequestsSuspensionRequestIdRoute
  '/activity/person/$personId/': typeof AppActivityPersonPersonIdIndexRoute
  '/activity/person/$personId/day/$day': typeof AppActivityPersonPersonIdDayDayRoute
}
export interface FileRoutesByTo {
  '/login': typeof unauthedLoginRoute
  '/people': typeof AppPeopleRoute
  '/signout': typeof AppSignoutRoute
  '/': typeof AppIndexRoute
  '/otp/$token': typeof unauthedOtpTokenRoute
  '/requests/suspension': typeof AppRequestsSuspensionRouteWithChildren
  '/requests/unlock': typeof AppRequestsUnlockRoute
  '/activity': typeof AppActivityIndexRoute
  '/activity/day/$day': typeof AppActivityDayDayRoute
  '/requests/suspension/$requestId': typeof AppRequestsSuspensionRequestIdRoute
  '/activity/person/$personId': typeof AppActivityPersonPersonIdIndexRoute
  '/activity/person/$personId/day/$day': typeof AppActivityPersonPersonIdDayDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/(unauthed)/login': typeof unauthedLoginRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/signout': typeof AppSignoutRoute
  '/_app/': typeof AppIndexRoute
  '/(unauthed)/otp/$token': typeof unauthedOtpTokenRoute
  '/_app/requests/suspension': typeof AppRequestsSuspensionRouteWithChildren
  '/_app/requests/unlock': typeof AppRequestsUnlockRoute
  '/_app/activity/': typeof AppActivityIndexRoute
  '/_app/activity/day/$day': typeof AppActivityDayDayRoute
  '/_app/requests/suspension/$requestId': typeof AppRequestsSuspensionRequestIdRoute
  '/_app/activity/person/$personId/': typeof AppActivityPersonPersonIdIndexRoute
  '/_app/activity/person/$personId/day/$day': typeof AppActivityPersonPersonIdDayDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/people'
    | '/signout'
    | '/otp/$token'
    | '/requests/suspension'
    | '/requests/unlock'
    | '/activity/'
    | '/activity/day/$day'
    | '/requests/suspension/$requestId'
    | '/activity/person/$personId/'
    | '/activity/person/$personId/day/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/people'
    | '/signout'
    | '/'
    | '/otp/$token'
    | '/requests/suspension'
    | '/requests/unlock'
    | '/activity'
    | '/activity/day/$day'
    | '/requests/suspension/$requestId'
    | '/activity/person/$personId'
    | '/activity/person/$personId/day/$day'
  id:
    | '__root__'
    | '/_app'
    | '/(unauthed)/login'
    | '/_app/people'
    | '/_app/signout'
    | '/_app/'
    | '/(unauthed)/otp/$token'
    | '/_app/requests/suspension'
    | '/_app/requests/unlock'
    | '/_app/activity/'
    | '/_app/activity/day/$day'
    | '/_app/requests/suspension/$requestId'
    | '/_app/activity/person/$personId/'
    | '/_app/activity/person/$personId/day/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  unauthedLoginRoute: typeof unauthedLoginRoute
  unauthedOtpTokenRoute: typeof unauthedOtpTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/signout': {
      id: '/_app/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof AppSignoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(unauthed)/login': {
      id: '/(unauthed)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthedLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity/': {
      id: '/_app/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AppActivityIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/requests/unlock': {
      id: '/_app/requests/unlock'
      path: '/requests/unlock'
      fullPath: '/requests/unlock'
      preLoaderRoute: typeof AppRequestsUnlockRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/requests/suspension': {
      id: '/_app/requests/suspension'
      path: '/requests/suspension'
      fullPath: '/requests/suspension'
      preLoaderRoute: typeof AppRequestsSuspensionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(unauthed)/otp/$token': {
      id: '/(unauthed)/otp/$token'
      path: '/otp/$token'
      fullPath: '/otp/$token'
      preLoaderRoute: typeof unauthedOtpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/requests/suspension/$requestId': {
      id: '/_app/requests/suspension/$requestId'
      path: '/$requestId'
      fullPath: '/requests/suspension/$requestId'
      preLoaderRoute: typeof AppRequestsSuspensionRequestIdRouteImport
      parentRoute: typeof AppRequestsSuspensionRoute
    }
    '/_app/activity/day/$day': {
      id: '/_app/activity/day/$day'
      path: '/activity/day/$day'
      fullPath: '/activity/day/$day'
      preLoaderRoute: typeof AppActivityDayDayRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/activity/person/$personId/': {
      id: '/_app/activity/person/$personId/'
      path: '/activity/person/$personId'
      fullPath: '/activity/person/$personId/'
      preLoaderRoute: typeof AppActivityPersonPersonIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/activity/person/$personId/day/$day': {
      id: '/_app/activity/person/$personId/day/$day'
      path: '/activity/person/$personId/day/$day'
      fullPath: '/activity/person/$personId/day/$day'
      preLoaderRoute: typeof AppActivityPersonPersonIdDayDayRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRequestsSuspensionRouteChildren {
  AppRequestsSuspensionRequestIdRoute: typeof AppRequestsSuspensionRequestIdRoute
}

const AppRequestsSuspensionRouteChildren: AppRequestsSuspensionRouteChildren = {
  AppRequestsSuspensionRequestIdRoute: AppRequestsSuspensionRequestIdRoute,
}

const AppRequestsSuspensionRouteWithChildren =
  AppRequestsSuspensionRoute._addFileChildren(
    AppRequestsSuspensionRouteChildren,
  )

interface AppRouteRouteChildren {
  AppPeopleRoute: typeof AppPeopleRoute
  AppSignoutRoute: typeof AppSignoutRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRequestsSuspensionRoute: typeof AppRequestsSuspensionRouteWithChildren
  AppRequestsUnlockRoute: typeof AppRequestsUnlockRoute
  AppActivityIndexRoute: typeof AppActivityIndexRoute
  AppActivityDayDayRoute: typeof AppActivityDayDayRoute
  AppActivityPersonPersonIdIndexRoute: typeof AppActivityPersonPersonIdIndexRoute
  AppActivityPersonPersonIdDayDayRoute: typeof AppActivityPersonPersonIdDayDayRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPeopleRoute: AppPeopleRoute,
  AppSignoutRoute: AppSignoutRoute,
  AppIndexRoute: AppIndexRoute,
  AppRequestsSuspensionRoute: AppRequestsSuspensionRouteWithChildren,
  AppRequestsUnlockRoute: AppRequestsUnlockRoute,
  AppActivityIndexRoute: AppActivityIndexRoute,
  AppActivityDayDayRoute: AppActivityDayDayRoute,
  AppActivityPersonPersonIdIndexRoute: AppActivityPersonPersonIdIndexRoute,
  AppActivityPersonPersonIdDayDayRoute: AppActivityPersonPersonIdDayDayRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  unauthedLoginRoute: unauthedLoginRoute,
  unauthedOtpTokenRoute: unauthedOtpTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
