/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSignoutRouteImport } from './routes/_app/signout'
import { Route as unauthedLoginRouteImport } from './routes/(unauthed)/login'
import { Route as AppPeopleRouteRouteImport } from './routes/_app/people/route'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppKeychainsIndexRouteImport } from './routes/_app/keychains/index'
import { Route as AppActivityIndexRouteImport } from './routes/_app/activity/index'
import { Route as AppRequestsUnlockRouteImport } from './routes/_app/requests/unlock'
import { Route as AppRequestsSuspensionRouteImport } from './routes/_app/requests/suspension'
import { Route as AppPeopleNewRouteImport } from './routes/_app/people/new'
import { Route as AppKeychainsKeychainIdRouteImport } from './routes/_app/keychains/$keychainId'
import { Route as unauthedOtpTokenRouteImport } from './routes/(unauthed)/otp/$token'
import { Route as AppPeoplePersonIdRouteRouteImport } from './routes/_app/people/$personId/route'
import { Route as AppPeoplePersonIdIndexRouteImport } from './routes/_app/people/$personId/index'
import { Route as AppRequestsSuspensionRequestIdRouteImport } from './routes/_app/requests/suspension/$requestId'
import { Route as AppPeoplePersonIdMacSettingsRouteImport } from './routes/_app/people/$personId/mac-settings'
import { Route as AppPeoplePersonIdIosSettingsRouteImport } from './routes/_app/people/$personId/ios-settings'
import { Route as AppActivityDayDayRouteImport } from './routes/_app/activity/day/$day'
import { Route as AppActivityPersonPersonIdIndexRouteImport } from './routes/_app/activity/person/$personId/index'
import { Route as AppActivityPersonPersonIdDayDayRouteImport } from './routes/_app/activity/person/$personId/day/$day'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignoutRoute = AppSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => AppRouteRoute,
} as any)
const unauthedLoginRoute = unauthedLoginRouteImport.update({
  id: '/(unauthed)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPeopleRouteRoute = AppPeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPeopleRouteRoute,
} as any)
const AppKeychainsIndexRoute = AppKeychainsIndexRouteImport.update({
  id: '/keychains/',
  path: '/keychains/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityIndexRoute = AppActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequestsUnlockRoute = AppRequestsUnlockRouteImport.update({
  id: '/requests/unlock',
  path: '/requests/unlock',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequestsSuspensionRoute = AppRequestsSuspensionRouteImport.update({
  id: '/requests/suspension',
  path: '/requests/suspension',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleNewRoute = AppPeopleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPeopleRouteRoute,
} as any)
const AppKeychainsKeychainIdRoute = AppKeychainsKeychainIdRouteImport.update({
  id: '/keychains/$keychainId',
  path: '/keychains/$keychainId',
  getParentRoute: () => AppRouteRoute,
} as any)
const unauthedOtpTokenRoute = unauthedOtpTokenRouteImport.update({
  id: '/(unauthed)/otp/$token',
  path: '/otp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPeoplePersonIdRouteRoute = AppPeoplePersonIdRouteRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => AppPeopleRouteRoute,
} as any)
const AppPeoplePersonIdIndexRoute = AppPeoplePersonIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPeoplePersonIdRouteRoute,
} as any)
const AppRequestsSuspensionRequestIdRoute =
  AppRequestsSuspensionRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => AppRequestsSuspensionRoute,
  } as any)
const AppPeoplePersonIdMacSettingsRoute =
  AppPeoplePersonIdMacSettingsRouteImport.update({
    id: '/mac-settings',
    path: '/mac-settings',
    getParentRoute: () => AppPeoplePersonIdRouteRoute,
  } as any)
const AppPeoplePersonIdIosSettingsRoute =
  AppPeoplePersonIdIosSettingsRouteImport.update({
    id: '/ios-settings',
    path: '/ios-settings',
    getParentRoute: () => AppPeoplePersonIdRouteRoute,
  } as any)
const AppActivityDayDayRoute = AppActivityDayDayRouteImport.update({
  id: '/activity/day/$day',
  path: '/activity/day/$day',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityPersonPersonIdIndexRoute =
  AppActivityPersonPersonIdIndexRouteImport.update({
    id: '/activity/person/$personId/',
    path: '/activity/person/$personId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppActivityPersonPersonIdDayDayRoute =
  AppActivityPersonPersonIdDayDayRouteImport.update({
    id: '/activity/person/$personId/day/$day',
    path: '/activity/person/$personId/day/$day',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/people': typeof AppPeopleRouteRouteWithChildren
  '/login': typeof unauthedLoginRoute
  '/signout': typeof AppSignoutRoute
  '/people/$personId': typeof AppPeoplePersonIdRouteRouteWithChildren
  '/otp/$token': typeof unauthedOtpTokenRoute
  '/keychains/$keychainId': typeof AppKeychainsKeychainIdRoute
  '/people/new': typeof AppPeopleNewRoute
  '/requests/suspension': typeof AppRequestsSuspensionRouteWithChildren
  '/requests/unlock': typeof AppRequestsUnlockRoute
  '/activity/': typeof AppActivityIndexRoute
  '/keychains/': typeof AppKeychainsIndexRoute
  '/people/': typeof AppPeopleIndexRoute
  '/activity/day/$day': typeof AppActivityDayDayRoute
  '/people/$personId/ios-settings': typeof AppPeoplePersonIdIosSettingsRoute
  '/people/$personId/mac-settings': typeof AppPeoplePersonIdMacSettingsRoute
  '/requests/suspension/$requestId': typeof AppRequestsSuspensionRequestIdRoute
  '/people/$personId/': typeof AppPeoplePersonIdIndexRoute
  '/activity/person/$personId/': typeof AppActivityPersonPersonIdIndexRoute
  '/activity/person/$personId/day/$day': typeof AppActivityPersonPersonIdDayDayRoute
}
export interface FileRoutesByTo {
  '/login': typeof unauthedLoginRoute
  '/signout': typeof AppSignoutRoute
  '/': typeof AppIndexRoute
  '/otp/$token': typeof unauthedOtpTokenRoute
  '/keychains/$keychainId': typeof AppKeychainsKeychainIdRoute
  '/people/new': typeof AppPeopleNewRoute
  '/requests/suspension': typeof AppRequestsSuspensionRouteWithChildren
  '/requests/unlock': typeof AppRequestsUnlockRoute
  '/activity': typeof AppActivityIndexRoute
  '/keychains': typeof AppKeychainsIndexRoute
  '/people': typeof AppPeopleIndexRoute
  '/activity/day/$day': typeof AppActivityDayDayRoute
  '/people/$personId/ios-settings': typeof AppPeoplePersonIdIosSettingsRoute
  '/people/$personId/mac-settings': typeof AppPeoplePersonIdMacSettingsRoute
  '/requests/suspension/$requestId': typeof AppRequestsSuspensionRequestIdRoute
  '/people/$personId': typeof AppPeoplePersonIdIndexRoute
  '/activity/person/$personId': typeof AppActivityPersonPersonIdIndexRoute
  '/activity/person/$personId/day/$day': typeof AppActivityPersonPersonIdDayDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/people': typeof AppPeopleRouteRouteWithChildren
  '/(unauthed)/login': typeof unauthedLoginRoute
  '/_app/signout': typeof AppSignoutRoute
  '/_app/': typeof AppIndexRoute
  '/_app/people/$personId': typeof AppPeoplePersonIdRouteRouteWithChildren
  '/(unauthed)/otp/$token': typeof unauthedOtpTokenRoute
  '/_app/keychains/$keychainId': typeof AppKeychainsKeychainIdRoute
  '/_app/people/new': typeof AppPeopleNewRoute
  '/_app/requests/suspension': typeof AppRequestsSuspensionRouteWithChildren
  '/_app/requests/unlock': typeof AppRequestsUnlockRoute
  '/_app/activity/': typeof AppActivityIndexRoute
  '/_app/keychains/': typeof AppKeychainsIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/activity/day/$day': typeof AppActivityDayDayRoute
  '/_app/people/$personId/ios-settings': typeof AppPeoplePersonIdIosSettingsRoute
  '/_app/people/$personId/mac-settings': typeof AppPeoplePersonIdMacSettingsRoute
  '/_app/requests/suspension/$requestId': typeof AppRequestsSuspensionRequestIdRoute
  '/_app/people/$personId/': typeof AppPeoplePersonIdIndexRoute
  '/_app/activity/person/$personId/': typeof AppActivityPersonPersonIdIndexRoute
  '/_app/activity/person/$personId/day/$day': typeof AppActivityPersonPersonIdDayDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/people'
    | '/login'
    | '/signout'
    | '/people/$personId'
    | '/otp/$token'
    | '/keychains/$keychainId'
    | '/people/new'
    | '/requests/suspension'
    | '/requests/unlock'
    | '/activity/'
    | '/keychains/'
    | '/people/'
    | '/activity/day/$day'
    | '/people/$personId/ios-settings'
    | '/people/$personId/mac-settings'
    | '/requests/suspension/$requestId'
    | '/people/$personId/'
    | '/activity/person/$personId/'
    | '/activity/person/$personId/day/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signout'
    | '/'
    | '/otp/$token'
    | '/keychains/$keychainId'
    | '/people/new'
    | '/requests/suspension'
    | '/requests/unlock'
    | '/activity'
    | '/keychains'
    | '/people'
    | '/activity/day/$day'
    | '/people/$personId/ios-settings'
    | '/people/$personId/mac-settings'
    | '/requests/suspension/$requestId'
    | '/people/$personId'
    | '/activity/person/$personId'
    | '/activity/person/$personId/day/$day'
  id:
    | '__root__'
    | '/_app'
    | '/_app/people'
    | '/(unauthed)/login'
    | '/_app/signout'
    | '/_app/'
    | '/_app/people/$personId'
    | '/(unauthed)/otp/$token'
    | '/_app/keychains/$keychainId'
    | '/_app/people/new'
    | '/_app/requests/suspension'
    | '/_app/requests/unlock'
    | '/_app/activity/'
    | '/_app/keychains/'
    | '/_app/people/'
    | '/_app/activity/day/$day'
    | '/_app/people/$personId/ios-settings'
    | '/_app/people/$personId/mac-settings'
    | '/_app/requests/suspension/$requestId'
    | '/_app/people/$personId/'
    | '/_app/activity/person/$personId/'
    | '/_app/activity/person/$personId/day/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  unauthedLoginRoute: typeof unauthedLoginRoute
  unauthedOtpTokenRoute: typeof unauthedOtpTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/signout': {
      id: '/_app/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof AppSignoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(unauthed)/login': {
      id: '/(unauthed)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthedLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppPeopleRouteRoute
    }
    '/_app/keychains/': {
      id: '/_app/keychains/'
      path: '/keychains'
      fullPath: '/keychains/'
      preLoaderRoute: typeof AppKeychainsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/activity/': {
      id: '/_app/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AppActivityIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/requests/unlock': {
      id: '/_app/requests/unlock'
      path: '/requests/unlock'
      fullPath: '/requests/unlock'
      preLoaderRoute: typeof AppRequestsUnlockRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/requests/suspension': {
      id: '/_app/requests/suspension'
      path: '/requests/suspension'
      fullPath: '/requests/suspension'
      preLoaderRoute: typeof AppRequestsSuspensionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people/new': {
      id: '/_app/people/new'
      path: '/new'
      fullPath: '/people/new'
      preLoaderRoute: typeof AppPeopleNewRouteImport
      parentRoute: typeof AppPeopleRouteRoute
    }
    '/_app/keychains/$keychainId': {
      id: '/_app/keychains/$keychainId'
      path: '/keychains/$keychainId'
      fullPath: '/keychains/$keychainId'
      preLoaderRoute: typeof AppKeychainsKeychainIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(unauthed)/otp/$token': {
      id: '/(unauthed)/otp/$token'
      path: '/otp/$token'
      fullPath: '/otp/$token'
      preLoaderRoute: typeof unauthedOtpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/people/$personId': {
      id: '/_app/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteRouteImport
      parentRoute: typeof AppPeopleRouteRoute
    }
    '/_app/people/$personId/': {
      id: '/_app/people/$personId/'
      path: '/'
      fullPath: '/people/$personId/'
      preLoaderRoute: typeof AppPeoplePersonIdIndexRouteImport
      parentRoute: typeof AppPeoplePersonIdRouteRoute
    }
    '/_app/requests/suspension/$requestId': {
      id: '/_app/requests/suspension/$requestId'
      path: '/$requestId'
      fullPath: '/requests/suspension/$requestId'
      preLoaderRoute: typeof AppRequestsSuspensionRequestIdRouteImport
      parentRoute: typeof AppRequestsSuspensionRoute
    }
    '/_app/people/$personId/mac-settings': {
      id: '/_app/people/$personId/mac-settings'
      path: '/mac-settings'
      fullPath: '/people/$personId/mac-settings'
      preLoaderRoute: typeof AppPeoplePersonIdMacSettingsRouteImport
      parentRoute: typeof AppPeoplePersonIdRouteRoute
    }
    '/_app/people/$personId/ios-settings': {
      id: '/_app/people/$personId/ios-settings'
      path: '/ios-settings'
      fullPath: '/people/$personId/ios-settings'
      preLoaderRoute: typeof AppPeoplePersonIdIosSettingsRouteImport
      parentRoute: typeof AppPeoplePersonIdRouteRoute
    }
    '/_app/activity/day/$day': {
      id: '/_app/activity/day/$day'
      path: '/activity/day/$day'
      fullPath: '/activity/day/$day'
      preLoaderRoute: typeof AppActivityDayDayRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/activity/person/$personId/': {
      id: '/_app/activity/person/$personId/'
      path: '/activity/person/$personId'
      fullPath: '/activity/person/$personId/'
      preLoaderRoute: typeof AppActivityPersonPersonIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/activity/person/$personId/day/$day': {
      id: '/_app/activity/person/$personId/day/$day'
      path: '/activity/person/$personId/day/$day'
      fullPath: '/activity/person/$personId/day/$day'
      preLoaderRoute: typeof AppActivityPersonPersonIdDayDayRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppPeoplePersonIdRouteRouteChildren {
  AppPeoplePersonIdIosSettingsRoute: typeof AppPeoplePersonIdIosSettingsRoute
  AppPeoplePersonIdMacSettingsRoute: typeof AppPeoplePersonIdMacSettingsRoute
  AppPeoplePersonIdIndexRoute: typeof AppPeoplePersonIdIndexRoute
}

const AppPeoplePersonIdRouteRouteChildren: AppPeoplePersonIdRouteRouteChildren =
  {
    AppPeoplePersonIdIosSettingsRoute: AppPeoplePersonIdIosSettingsRoute,
    AppPeoplePersonIdMacSettingsRoute: AppPeoplePersonIdMacSettingsRoute,
    AppPeoplePersonIdIndexRoute: AppPeoplePersonIdIndexRoute,
  }

const AppPeoplePersonIdRouteRouteWithChildren =
  AppPeoplePersonIdRouteRoute._addFileChildren(
    AppPeoplePersonIdRouteRouteChildren,
  )

interface AppPeopleRouteRouteChildren {
  AppPeoplePersonIdRouteRoute: typeof AppPeoplePersonIdRouteRouteWithChildren
  AppPeopleNewRoute: typeof AppPeopleNewRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppPeopleRouteRouteChildren: AppPeopleRouteRouteChildren = {
  AppPeoplePersonIdRouteRoute: AppPeoplePersonIdRouteRouteWithChildren,
  AppPeopleNewRoute: AppPeopleNewRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppPeopleRouteRouteWithChildren = AppPeopleRouteRoute._addFileChildren(
  AppPeopleRouteRouteChildren,
)

interface AppRequestsSuspensionRouteChildren {
  AppRequestsSuspensionRequestIdRoute: typeof AppRequestsSuspensionRequestIdRoute
}

const AppRequestsSuspensionRouteChildren: AppRequestsSuspensionRouteChildren = {
  AppRequestsSuspensionRequestIdRoute: AppRequestsSuspensionRequestIdRoute,
}

const AppRequestsSuspensionRouteWithChildren =
  AppRequestsSuspensionRoute._addFileChildren(
    AppRequestsSuspensionRouteChildren,
  )

interface AppRouteRouteChildren {
  AppPeopleRouteRoute: typeof AppPeopleRouteRouteWithChildren
  AppSignoutRoute: typeof AppSignoutRoute
  AppIndexRoute: typeof AppIndexRoute
  AppKeychainsKeychainIdRoute: typeof AppKeychainsKeychainIdRoute
  AppRequestsSuspensionRoute: typeof AppRequestsSuspensionRouteWithChildren
  AppRequestsUnlockRoute: typeof AppRequestsUnlockRoute
  AppActivityIndexRoute: typeof AppActivityIndexRoute
  AppKeychainsIndexRoute: typeof AppKeychainsIndexRoute
  AppActivityDayDayRoute: typeof AppActivityDayDayRoute
  AppActivityPersonPersonIdIndexRoute: typeof AppActivityPersonPersonIdIndexRoute
  AppActivityPersonPersonIdDayDayRoute: typeof AppActivityPersonPersonIdDayDayRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPeopleRouteRoute: AppPeopleRouteRouteWithChildren,
  AppSignoutRoute: AppSignoutRoute,
  AppIndexRoute: AppIndexRoute,
  AppKeychainsKeychainIdRoute: AppKeychainsKeychainIdRoute,
  AppRequestsSuspensionRoute: AppRequestsSuspensionRouteWithChildren,
  AppRequestsUnlockRoute: AppRequestsUnlockRoute,
  AppActivityIndexRoute: AppActivityIndexRoute,
  AppKeychainsIndexRoute: AppKeychainsIndexRoute,
  AppActivityDayDayRoute: AppActivityDayDayRoute,
  AppActivityPersonPersonIdIndexRoute: AppActivityPersonPersonIdIndexRoute,
  AppActivityPersonPersonIdDayDayRoute: AppActivityPersonPersonIdDayDayRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  unauthedLoginRoute: unauthedLoginRoute,
  unauthedOtpTokenRoute: unauthedOtpTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
