import 'watch-helpers.just'

mod macapp

set dotenv-filename := "../.gtask-ports"
set dotenv-required := false

api_port := env("API_PORT", "8080")
ngrok_subdomain := env("NGROK_SUBDOMAIN", "")
swiftly := "${SWIFTLY_HOME_DIR:-$HOME/.swiftly}/bin/swiftly"

_default:
  @just --choose

# ios

watch-ios:
  @just watch-build iosapp/lib-ios

iosapp:
  @open iosapp/Gertrude-iOS.xcodeproj

iosapp-xcode-build:
  @pnpm exec nx run iosapp:xcode-build

browser-xcode-build:
  @pnpm exec nx run browser:xcode-build

iosconfig:
  @echo "LOCAL_API_URL = https:/\$()/{{ngrok_subdomain}}.ngrok-free.app" > iosapp/config/Local.xcconfig

ios-tunnel:
  @pkill -f ngrok || true
  @ngrok http {{api_port}} --url https://{{ngrok_subdomain}}.ngrok-free.app

# api

watch-api:
  @just watch-swift . 'just run-api' 'macapp/**/*'

run-api: build-api
  @just exec-api serve --port {{api_port}}

run-api-ip: build-api
  @just exec-api serve --hostname 192.168.10.248

build-api:
  @cd api && {{swiftly}} run swift build

api-build:
  @just build-api

api-test *args:
  @cd api && SWIFT_DETERMINISTIC_HASHING=1 {{swiftly}} run swift test {{args}}

macapp-test *args:
  @cd macapp/App && SWIFT_DETERMINISTIC_HASHING=1 {{swiftly}} run swift test {{args}}

iosapp-test *args:
  @cd iosapp/lib-ios && SWIFT_DETERMINISTIC_HASHING=1 {{swiftly}} run swift test {{args}}

migrate-up: build-api
  @just exec-api migrate --yes

migrate-down: build-api
  @just exec-api migrate --revert --yes

reset: build-api
  just exec-api reset

sync-staging-data: build-api
  @just exec-api sync-staging-data

nuke-test-db:
  @killall -q Postico; db=$(grep '^TEST_DATABASE_NAME=' api/.env | cut -d= -f2); dropdb --if-exists --force "$db"; createdb "$db"

hurl-dev *args:
  @hurl --variable API_URL="http://127.0.0.1:{{api_port}}" {{args}}

hurl-prod *args:
  @hurl --variable API_URL="https://api.gertrude.app" api/hurl/prod.env {{args}}

# emails (requires local dev api running)

send-email template:
  @curl http://127.0.0.1:{{api_port}}/send-test-email/{{template}}

sync-email-templates:
  @curl http://127.0.0.1:{{api_port}}/sync-email-templates

web-email template:
  @curl -s http://127.0.0.1:{{api_port}}/web-test-email/{{template}}

# NB: requires `concurrently`, `vite` in $PATH
watch-web-email template:
  @concurrently -n serve,regen -c cyan.dim,magenta.dim \
    "vite" \
    "bash -c 'while true; do just web-email {{template}}; sleep 2; done;'" \
    "cd dev-emails && npm run dev"

# infra

db-sync:
  @node ../infra/db-sync.mjs

# root

build:
  @just nx-run-many build

test:
  @just nx-run-many test

lint-swift:
  @swiftformat . --lint

format:
  @swiftformat .

lint-xml:
  @xml-lint {{xmlfiles}}

lint-xml-fix:
  @xml-lint --fix {{xmlfiles}}

lint:
  @just lint-swift
  @just lint-xml

fix:
  @just lint-xml-fix
  @just format

check:
  @just build
  @just macapp xcode-build
  @just iosapp-xcode-build
  @just browser-xcode-build
  @just test
  @just lint

nx-reset:
  @pnpm nx reset

clean: nx-reset
  @rm -rf node_modules/.cache
  @rm -rf api/.build duet/.build gertie/.build
  @rm -rf macapp/App/.build iosapp/lib-ios/.build
  @rm -rf pairql/.build pairql-macapp/.build pairql-iosapp/.build
  @rm -rf ts-interop/.build x-aws/.build x-http/.build
  @rm -rf x-kit/.build x-postmark/.build x-slack/.build x-stripe/.build

# helpers

[private]
exec-api cmd *args:
  @cd api && ./.build/debug/Run {{cmd}} {{args}}

[private]
nx-run-many targets:
  @pnpm exec nx run-many --parallel=10 --targets={{targets}}

# variables

xmlfiles := """
./iosapp/app/app.entitlements \
./iosapp/app/Info.plist \
./iosapp/controller/controller.entitlements \
./iosapp/controller/Info.plist \
./iosapp/filter/filter.entitlements \
./iosapp/filter/Info.plist \
./macapp/Xcode/GertrudeFilterExtension/GertrudeFilterExtension.entitlements \
./macapp/Xcode/GertrudeFilterExtension/Info.plist \
./macapp/Xcode/Gertrude/Gertrude.entitlements \
./macapp/Xcode/Gertrude/Info.plist \
./macapp/Xcode/GertrudeRelauncher/GertrudeRelauncher.entitlements \
./podcasts/app/Info.plist \
./browser/app/Info.plist
"""
