name: GertiePodcasts
options:
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  knownRegions:
    - en
    - es
    - Base

configs:
  Debug: debug
  Release: release

targets:
  'Gertrude AM':
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: app/sources
        group: app
      - path: app/Assets.xcassets
        group: app
      - path: app/LaunchScreen.storyboard
        group: app
      - path: app/StoreConfig.storekit
        buildPhase: none
        group: app
    dependencies:
      - package: LibCore
      - package: LibViews
      - package: LibTCA
    settings:
      base:
        DEVELOPMENT_TEAM: "WFN83LM943"
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: app/Info.plist
        MARKETING_VERSION: 1.3.0
        CURRENT_PROJECT_VERSION: 19
      configs:
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: "com.netrivet.gertrude.am"
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          API_ENDPOINT: "https://api.gertrude.app"
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: "com.netrivet.gertrude.am.dev"
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIconDev
          API_ENDPOINT: "http://192.168.10.248:8080" # - run-api-ip
    scheme:
      storeKitConfiguration: "app/StoreConfig.storekit"
    info:
      path: app/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: Gertrude AM
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleLocalizations:
          - en
          - es
        API_ENDPOINT: $(API_ENDPOINT)
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        UILaunchStoryboardName: LaunchScreen
        UIBackgroundModes:
          - audio
          - fetch
          - processing
        BGTaskSchedulerPermittedIdentifiers:
          # NB: keep in sync with keys in BackgroundTasks.swift
          - com.netrivet.gertrude.am.refresh-feed
          - com.netrivet.gertrude.am.download-episodes

packages:
  LibCore:
    path: ./lib-core
  LibViews:
    path: ./lib-views
  LibTCA:
    path: ./lib-tca
