name: GertiePodcasts
options:
  deploymentTarget:
    iOS: "18.0"

targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: app/sources
        group: app
      - path: app/Assets.xcassets
        group: app
    dependencies:
      - package: LibCore
      - package: LibViews
      - package: LibTCA
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.netrivet.gertrude.podcasts"
      DEVELOPMENT_TEAM: "WFN83LM943"
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: app/Info.plist
      MARKETING_VERSION: 0.0.1
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: app/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: Gertrude AM
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        UILaunchStoryboardName: LaunchScreen
        UIBackgroundModes:
          - audio
          - background-fetch
          - background-processing
        BGTaskSchedulerPermittedIdentifiers:
          # NB: keep in sync with keys in BackgroundTasks.swift
          - com.netrivet.gertrude.podcasts.refresh-feed
          - com.netrivet.gertrude.podcasts.download-episodes

packages:
  LibCore:
    path: ./lib-core
  LibViews:
    path: ./lib-views
  LibTCA:
    path: ./lib-tca
