/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSignoutRouteImport } from './routes/_app/signout'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppAppsRouteImport } from './routes/_app/apps'
import { Route as unauthedSignupRouteImport } from './routes/(unauthed)/signup'
import { Route as unauthedLoginRouteImport } from './routes/(unauthed)/login'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignoutRoute = AppSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppsRoute = AppAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppRouteRoute,
} as any)
const unauthedSignupRoute = unauthedSignupRouteImport.update({
  id: '/(unauthed)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const unauthedLoginRoute = unauthedLoginRouteImport.update({
  id: '/(unauthed)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/login': typeof unauthedLoginRoute
  '/signup': typeof unauthedSignupRoute
  '/apps': typeof AppAppsRoute
  '/devices': typeof AppDevicesRoute
  '/people': typeof AppPeopleRoute
  '/signout': typeof AppSignoutRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/login': typeof unauthedLoginRoute
  '/signup': typeof unauthedSignupRoute
  '/apps': typeof AppAppsRoute
  '/devices': typeof AppDevicesRoute
  '/people': typeof AppPeopleRoute
  '/signout': typeof AppSignoutRoute
  '/': typeof AppIndexRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/(unauthed)/login': typeof unauthedLoginRoute
  '/(unauthed)/signup': typeof unauthedSignupRoute
  '/_app/apps': typeof AppAppsRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/signout': typeof AppSignoutRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/signup'
    | '/apps'
    | '/devices'
    | '/people'
    | '/signout'
    | '/settings/billing'
    | '/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/login'
    | '/signup'
    | '/apps'
    | '/devices'
    | '/people'
    | '/signout'
    | '/'
    | '/settings/billing'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/(unauthed)/login'
    | '/(unauthed)/signup'
    | '/_app/apps'
    | '/_app/devices'
    | '/_app/people'
    | '/_app/signout'
    | '/_app/'
    | '/_app/settings/billing'
    | '/_app/settings/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  unauthedLoginRoute: typeof unauthedLoginRoute
  unauthedSignupRoute: typeof unauthedSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/signout': {
      id: '/_app/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof AppSignoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/apps': {
      id: '/_app/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppAppsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(unauthed)/signup': {
      id: '/(unauthed)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof unauthedSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unauthed)/login': {
      id: '/(unauthed)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthedLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppAppsRoute: typeof AppAppsRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppSignoutRoute: typeof AppSignoutRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppAppsRoute: AppAppsRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppSignoutRoute: AppSignoutRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  unauthedLoginRoute: unauthedLoginRoute,
  unauthedSignupRoute: unauthedSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
