import { BatchUnlockRequests } from '@dash/components';
import type { Meta, StoryObj } from '@storybook/react';
import { withStatefulChrome } from '../../decorators/StatefulChrome';
import { fixedViewport, keychainProps, props, time } from '../../story-helpers';

const meta = {
  title: 'Dashboard/Children/BatchUnlockRequests',
  component: BatchUnlockRequests,
  parameters: { layout: `fullscreen` },
  decorators: [withStatefulChrome],
} satisfies Meta<typeof BatchUnlockRequests>;

type Story = StoryObj<typeof meta>;

const keychains = [
  keychainProps({ id: `kc-1`, name: `Dale's Keys`, numKeys: 47 }),
  keychainProps({ id: `kc-2`, name: `School Stuff`, numKeys: 12 }),
  keychainProps({
    id: `kc-3`,
    name: `Music Theory & Ear Training Resources`,
    numKeys: 3,
  }),
];

export const Default: Story = props({
  childName: `Huck`,
  keychains,
  requests: [
    {
      id: `1`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      url: `https://a22314-891616.cluster308.canvas-user-content.com/courses/22314~2172/files/22314~891616/course%20files/Uploaded%20Media/Edgar%20Allan%20Poe%20Culminating%20Activity%20Quarter%203.pdf?download_frd=1&sf_verifier=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoiMjIzMTQwMDAwMDAwMDA1NjEwIn0.qPoJFYGoTrB8b9b50RBVLTLn7QINPdC9ctD2_sC9h3I`,
      domain: `a22314-891616.cluster308.canvas-user-content.com`,
      ipAddress: `44.237.108.181`,
      requestComment: `class`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 2 }),
    },
    {
      id: `2`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      url: `https://www.googleadservices.com/pagead/conversion/16689205740/?random=1774539821005&cv=11&fst=1774539821005&bg=ffffff&guid=ON&async=1&gtm=45je5bt0v9184919959za200&gcd=13l3l3l3l1l1&dma=0&tag_exp=0&u_w=1440&u_h=900&url=https%3A%2F%2Fwww.comickids.org%2F&hn=www.googletagmanager.com`,
      domain: `www.googleadservices.com`,
      ipAddress: `142.251.210.98`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 5 }),
    },
    {
      id: `3`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      domain: `natcapwg.cap.gov`,
      ipAddress: `216.81.136.20`,
      requestComment: `it is a word website for writing professional documents and i need it for school`,
      appName: `Firefox`,
      appBundleId: `43AQ936H96.org.mozilla.firefox`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 12 }),
    },
    {
      id: `4`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      ipAddress: `99.81.103.55`,
      requestComment: `They may sound like war tunder bbut tey aere coming from comic kids`,
      appName: undefined,
      appBundleId: `4P553833NY.com.gaijinent.WarThunder`,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 20 }),
    },
    {
      id: `5`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      url: `https://www.google.com/ccm/collect?frm=0&en=page_view&dl=https%3A%2F%2Fwww.comickids.org%2F&scrsrc=www.googletagmanager.com&fmts=AW-16689205740&did=dZTNEf&gdid=dZTNEf&aession_id=1774534981&edid=CAESELjc_RexmYoSsYq-l8&frm=0&tag_exp=0&srct=tag_candidates&dns=d&tfd=3721&trip_id=CA&rnd=1`,
      domain: `www.google.com`,
      ipAddress: `142.251.153.119`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 30 }),
    },
    {
      id: `6`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      url: `https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/c7/86/9f/c7869f75-d9b5-74c6-f834-6fd9a9d862f0/maps_2025-0-1x_U007epad-0-0-0-1-0-0-0-0-85-220-0.png/72x72bb.jpg`,
      domain: `is1-ssl.mzstatic.com`,
      ipAddress: `199.232.47.6`,
      requestComment: `Apple URLs`,
      appName: undefined,
      appBundleId: `.com.apple.Screen-Time-Settings.extension`,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 45 }),
    },
    {
      id: `7`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      domain: `remotedesktop.google.com`,
      ipAddress: `142.251.210.238`,
      requestComment: `Thing to put docs on`,
      appName: `Chrome`,
      appBundleId: `EQHXZ8M8AV.com.google.Chrome.helper`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ hours: 1 }),
    },
    {
      id: `8`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      url: `wss://capi.grammarly.com/fpws?accessToken=eyJ2ZXIiOiJWMyIsInR5cCI6ImF0K2p3dCIsInZlcnNpb24iOiIzIiwiYWxnIjoiUlMyNTYiLCJraWQiOiI3ZjRkNDdmNy02MTdkLTQ3YjItYmYxNS1lMmRkNGY3MjY3YTgifQ.eyJzdWIiOiIxNzMxNTIzNjk5Iiwic2NvcGUiOiJ1c2VyIiwidGVuYW50SWQiOiIxNzMxNTIzNjk5In0.signature`,
      domain: `capi.grammarly.com`,
      ipAddress: `52.5.45.120`,
      appName: undefined,
      appBundleId: `com.grammarly.ProjectLlama`,
      appCategories: [],
      createdAt: time.subtracting({ hours: 2 }),
    },
  ],
});

export const TwoRequests: Story = props({
  childName: `Sally`,
  keychains,
  requests: [
    {
      id: `1`,
      userId: `user-sally`,
      userName: `Sally`,
      status: `pending` as const,
      domain: `geofs.com`,
      url: `http://geofs.com/`,
      ipAddress: `174.77.82.187`,
      requestComment: `unlock pls aero for phhys`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 3 }),
    },
    {
      id: `2`,
      userId: `user-sally`,
      userName: `Sally`,
      status: `pending` as const,
      ipAddress: `35.241.1.16`,
      requestComment: `Yo`,
      appName: `Firefox`,
      appBundleId: `43AQ936H96.org.mozilla.firefox`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 10 }),
    },
  ],
});

export const SingleRequest: Story = props({
  childName: `Freddy`,
  keychains,
  requests: [
    {
      id: `1`,
      userId: `user-freddy`,
      userName: `Freddy`,
      status: `pending` as const,
      url: `https://calendar-pa.clients6.google.com/$rpc/google.internal.calendar.v1.AppointmentBookingService/GetAppointmentServiceAvailability?key=AIzaSyBNlYH01_9Hc5S1J9vuFmu2nUqBZJNAXxs`,
      domain: `calendar-pa.clients6.google.com`,
      ipAddress: `142.250.73.138`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 1 }),
    },
  ],
});

export const WithDuplicates: Story = props({
  childName: `Dale`,
  keychains,
  requests: [
    {
      id: `d1`,
      userId: `user-dale`,
      userName: `Dale`,
      status: `pending` as const,
      url: `https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:quadratics`,
      domain: `www.khanacademy.org`,
      ipAddress: `151.101.1.42`,
      requestComment: `need this for math class`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 2 }),
    },
    {
      id: `d2`,
      userId: `user-dale`,
      userName: `Dale`,
      status: `pending` as const,
      url: `https://www.khanacademy.org/science/biology/gene-expression`,
      domain: `www.khanacademy.org`,
      ipAddress: `151.101.1.42`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 5 }),
    },
    {
      id: `d3`,
      userId: `user-dale`,
      userName: `Dale`,
      status: `pending` as const,
      url: `https://www.khanacademy.org/computing/computer-science/algorithms`,
      domain: `www.khanacademy.org`,
      ipAddress: `151.101.1.42`,
      requestComment: `also need for CS class`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 8 }),
    },
    {
      id: `d4`,
      userId: `user-dale`,
      userName: `Dale`,
      status: `pending` as const,
      url: `https://docs.google.com/document/d/1abc123/edit`,
      domain: `docs.google.com`,
      ipAddress: `142.251.210.98`,
      requestComment: `shared doc for group project`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 10 }),
    },
    {
      id: `d5`,
      userId: `user-dale`,
      userName: `Dale`,
      status: `pending` as const,
      url: `https://docs.google.com/spreadsheets/d/1xyz789/edit`,
      domain: `docs.google.com`,
      ipAddress: `142.251.210.99`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 15 }),
    },
    {
      id: `d6`,
      userId: `user-dale`,
      userName: `Dale`,
      status: `pending` as const,
      domain: `natcapwg.cap.gov`,
      ipAddress: `216.81.136.20`,
      appName: `Firefox`,
      appBundleId: `43AQ936H96.org.mozilla.firefox`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 20 }),
    },
    {
      id: `d7`,
      userId: `user-dale`,
      userName: `Dale`,
      status: `pending` as const,
      ipAddress: `99.81.103.55`,
      requestComment: `game server`,
      appName: undefined,
      appBundleId: `4P553833NY.com.gaijinent.WarThunder`,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 25 }),
    },
  ],
});

export const WithNaughtyDomains: Story = props({
  childName: `Huck`,
  keychains,
  requests: [
    {
      id: `n1`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      url: `https://www.youtube.com/watch?v=dQw4w9WgXcQ`,
      domain: `www.youtube.com`,
      ipAddress: `142.251.210.46`,
      requestComment: `need for school project video`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 2 }),
    },
    {
      id: `n2`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      domain: `www.khanacademy.org`,
      url: `https://www.khanacademy.org/math/algebra`,
      ipAddress: `151.101.1.42`,
      requestComment: `math homework`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 5 }),
    },
    {
      id: `n3`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      url: `https://www.reddit.com/r/homework`,
      domain: `www.reddit.com`,
      ipAddress: `151.101.129.140`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 10 }),
    },
    {
      id: `n4`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      domain: `chatgpt.com`,
      ipAddress: `104.18.32.7`,
      requestComment: `need for writing assignment`,
      appName: `Chrome`,
      appBundleId: `EQHXZ8M8AV.com.google.Chrome.helper`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 15 }),
    },
    {
      id: `n5`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      url: `https://googleads.g.doubleclick.net/pagead/id`,
      domain: `googleads.g.doubleclick.net`,
      ipAddress: `142.251.210.98`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 20 }),
    },
    {
      id: `n6`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      domain: `play.blooket.com`,
      url: `https://play.blooket.com/play`,
      ipAddress: `76.76.21.21`,
      requestComment: `teacher uses this for review games`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 25 }),
    },
    {
      id: `n7`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      domain: `www.google.com`,
      url: `https://www.google.com/search?q=math+help`,
      ipAddress: `142.251.153.119`,
      requestComment: `need to search for homework help`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 30 }),
    },
    {
      id: `n8`,
      userId: `user-huck`,
      userName: `Huck`,
      status: `pending` as const,
      domain: `en.wikipedia.org`,
      url: `https://en.wikipedia.org/wiki/American_Revolution`,
      ipAddress: `208.80.154.224`,
      requestComment: `research for history essay`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 35 }),
    },
  ],
});

const unityIcon = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32'%3E%3Crect width='32' height='32' rx='7' fill='%23222c37'/%3E%3Cpath d='M16 7l7 4v10l-7 4-7-4V11z' fill='%23fff'/%3E%3C/svg%3E`;
const minecraftIcon = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32'%3E%3Crect width='32' height='32' rx='7' fill='%237cb342'/%3E%3Crect x='8' y='8' width='7' height='7' fill='%23558b2f'/%3E%3Crect x='17' y='17' width='7' height='7' fill='%23558b2f'/%3E%3C/svg%3E`;

const appRequestsArgs = props({
  childName: `Leo`,
  keychains,
  requests: [
    // Unity Hub whack-a-mole: one app, four distinct hosts, all app-scoped
    {
      id: `u1`,
      userId: `user-leo`,
      userName: `Leo`,
      status: `pending` as const,
      domain: `config.unity3d.com`,
      ipAddress: `35.190.85.1`,
      requestComment: `trying to open my game project`,
      appName: `Unity Hub`,
      appSlug: `unity-hub`,
      appBundleId: `com.unity3d.unityhub`,
      appIconHash: unityIcon,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 2 }),
    },
    {
      id: `u2`,
      userId: `user-leo`,
      userName: `Leo`,
      status: `pending` as const,
      domain: `api.unity.com`,
      ipAddress: `104.16.90.1`,
      appName: `Unity Hub`,
      appSlug: `unity-hub`,
      appBundleId: `com.unity3d.unityhub`,
      appIconHash: unityIcon,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 3 }),
    },
    {
      id: `u3`,
      userId: `user-leo`,
      userName: `Leo`,
      status: `pending` as const,
      domain: `cdn.unitycloud.com`,
      ipAddress: `151.101.1.5`,
      appName: `Unity Hub`,
      appSlug: `unity-hub`,
      appBundleId: `com.unity3d.unityhub`,
      appIconHash: unityIcon,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 4 }),
    },
    {
      id: `u4`,
      userId: `user-leo`,
      userName: `Leo`,
      status: `pending` as const,
      domain: `analytics.unity-cdn.net`,
      ipAddress: `18.66.1.9`,
      appName: `Unity Hub`,
      appSlug: `unity-hub`,
      appBundleId: `com.unity3d.unityhub`,
      appIconHash: unityIcon,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 5 }),
    },
    // cataloged app with icon, two hosts
    {
      id: `m1`,
      userId: `user-leo`,
      userName: `Leo`,
      status: `pending` as const,
      domain: `authserver.mojang.com`,
      ipAddress: `13.107.6.1`,
      requestComment: `log in to minecraft`,
      appName: `Minecraft`,
      appSlug: `minecraft`,
      appBundleId: `com.mojang.minecraft`,
      appIconHash: minecraftIcon,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 8 }),
    },
    {
      id: `m2`,
      userId: `user-leo`,
      userName: `Leo`,
      status: `pending` as const,
      domain: `sessionserver.mojang.net`,
      ipAddress: `13.107.6.2`,
      appName: `Minecraft`,
      appSlug: `minecraft`,
      appBundleId: `com.mojang.minecraft`,
      appIconHash: minecraftIcon,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 9 }),
    },
    // unidentified app (bundleId only) → defaults to "Allow addresses"
    {
      id: `w1`,
      userId: `user-leo`,
      userName: `Leo`,
      status: `pending` as const,
      ipAddress: `99.81.103.55`,
      requestComment: `war thunder wont connect`,
      appName: undefined,
      appBundleId: `4P553833NY.com.gaijinent.WarThunder`,
      appCategories: [],
      createdAt: time.subtracting({ minutes: 14 }),
    },
    // browser web rows for contrast
    {
      id: `b1`,
      userId: `user-leo`,
      userName: `Leo`,
      status: `pending` as const,
      domain: `www.youtube.com`,
      url: `https://www.youtube.com/watch?v=xyz`,
      ipAddress: `142.251.153.1`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 18 }),
    },
    {
      id: `b2`,
      userId: `user-leo`,
      userName: `Leo`,
      status: `pending` as const,
      domain: `www.khanacademy.org`,
      url: `https://www.khanacademy.org/math`,
      ipAddress: `151.101.1.42`,
      requestComment: `math practice`,
      appName: `Safari`,
      appBundleId: `.com.apple.Safari`,
      appCategories: [`browser`],
      createdAt: time.subtracting({ minutes: 22 }),
    },
  ],
});

export const AppRequests: Story = appRequestsArgs;

export const AppRequestsMobile: Story = {
  ...appRequestsArgs,
  ...fixedViewport(390, 844),
};

export const Mobile: Story = {
  ...props({
    ...Default.args!,
  }),
  ...fixedViewport(390, 844),
};

export default meta;
