/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsSidebarRouteImport } from './routes/components/sidebar'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsFormRouteImport } from './routes/components/form'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSidebarRoute = ComponentsSidebarRouteImport.update({
  id: '/components/sidebar',
  path: '/components/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/components/input',
  path: '/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormRoute = ComponentsFormRouteImport.update({
  id: '/components/form',
  path: '/components/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/form': typeof ComponentsFormRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/form': typeof ComponentsFormRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/form': typeof ComponentsFormRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/form'
    | '/components/input'
    | '/components/select'
    | '/components/sidebar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/form'
    | '/components/input'
    | '/components/select'
    | '/components/sidebar'
  id:
    | '__root__'
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/form'
    | '/components/input'
    | '/components/select'
    | '/components/sidebar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsFormRoute: typeof ComponentsFormRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSidebarRoute: typeof ComponentsSidebarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/sidebar': {
      id: '/components/sidebar'
      path: '/components/sidebar'
      fullPath: '/components/sidebar'
      preLoaderRoute: typeof ComponentsSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input': {
      id: '/components/input'
      path: '/components/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/form': {
      id: '/components/form'
      path: '/components/form'
      fullPath: '/components/form'
      preLoaderRoute: typeof ComponentsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/components/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsFormRoute: ComponentsFormRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSidebarRoute: ComponentsSidebarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
