/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsToggleRouteImport } from './routes/components/toggle'
import { Route as ComponentsTextareaRouteImport } from './routes/components/textarea'
import { Route as ComponentsSidebarRouteImport } from './routes/components/sidebar'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsRadioGroupRouteImport } from './routes/components/radio-group'
import { Route as ComponentsPageHeadingRouteImport } from './routes/components/page-heading'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsFormRouteImport } from './routes/components/form'
import { Route as ComponentsDropdownMenuRouteImport } from './routes/components/dropdown-menu'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsToggleRoute = ComponentsToggleRouteImport.update({
  id: '/components/toggle',
  path: '/components/toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextareaRoute = ComponentsTextareaRouteImport.update({
  id: '/components/textarea',
  path: '/components/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSidebarRoute = ComponentsSidebarRouteImport.update({
  id: '/components/sidebar',
  path: '/components/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRadioGroupRoute = ComponentsRadioGroupRouteImport.update({
  id: '/components/radio-group',
  path: '/components/radio-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPageHeadingRoute = ComponentsPageHeadingRouteImport.update({
  id: '/components/page-heading',
  path: '/components/page-heading',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/components/input',
  path: '/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormRoute = ComponentsFormRouteImport.update({
  id: '/components/form',
  path: '/components/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDropdownMenuRoute = ComponentsDropdownMenuRouteImport.update({
  id: '/components/dropdown-menu',
  path: '/components/dropdown-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/form': typeof ComponentsFormRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/page-heading': typeof ComponentsPageHeadingRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toggle': typeof ComponentsToggleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/form': typeof ComponentsFormRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/page-heading': typeof ComponentsPageHeadingRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toggle': typeof ComponentsToggleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/form': typeof ComponentsFormRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/page-heading': typeof ComponentsPageHeadingRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toggle': typeof ComponentsToggleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/checkbox'
    | '/components/dropdown-menu'
    | '/components/form'
    | '/components/input'
    | '/components/page-heading'
    | '/components/radio-group'
    | '/components/select'
    | '/components/sidebar'
    | '/components/textarea'
    | '/components/toggle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/checkbox'
    | '/components/dropdown-menu'
    | '/components/form'
    | '/components/input'
    | '/components/page-heading'
    | '/components/radio-group'
    | '/components/select'
    | '/components/sidebar'
    | '/components/textarea'
    | '/components/toggle'
  id:
    | '__root__'
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/checkbox'
    | '/components/dropdown-menu'
    | '/components/form'
    | '/components/input'
    | '/components/page-heading'
    | '/components/radio-group'
    | '/components/select'
    | '/components/sidebar'
    | '/components/textarea'
    | '/components/toggle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsDropdownMenuRoute: typeof ComponentsDropdownMenuRoute
  ComponentsFormRoute: typeof ComponentsFormRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsPageHeadingRoute: typeof ComponentsPageHeadingRoute
  ComponentsRadioGroupRoute: typeof ComponentsRadioGroupRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSidebarRoute: typeof ComponentsSidebarRoute
  ComponentsTextareaRoute: typeof ComponentsTextareaRoute
  ComponentsToggleRoute: typeof ComponentsToggleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/toggle': {
      id: '/components/toggle'
      path: '/components/toggle'
      fullPath: '/components/toggle'
      preLoaderRoute: typeof ComponentsToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/textarea': {
      id: '/components/textarea'
      path: '/components/textarea'
      fullPath: '/components/textarea'
      preLoaderRoute: typeof ComponentsTextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/sidebar': {
      id: '/components/sidebar'
      path: '/components/sidebar'
      fullPath: '/components/sidebar'
      preLoaderRoute: typeof ComponentsSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/radio-group': {
      id: '/components/radio-group'
      path: '/components/radio-group'
      fullPath: '/components/radio-group'
      preLoaderRoute: typeof ComponentsRadioGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/page-heading': {
      id: '/components/page-heading'
      path: '/components/page-heading'
      fullPath: '/components/page-heading'
      preLoaderRoute: typeof ComponentsPageHeadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input': {
      id: '/components/input'
      path: '/components/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/form': {
      id: '/components/form'
      path: '/components/form'
      fullPath: '/components/form'
      preLoaderRoute: typeof ComponentsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dropdown-menu': {
      id: '/components/dropdown-menu'
      path: '/components/dropdown-menu'
      fullPath: '/components/dropdown-menu'
      preLoaderRoute: typeof ComponentsDropdownMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/components/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsDropdownMenuRoute: ComponentsDropdownMenuRoute,
  ComponentsFormRoute: ComponentsFormRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsPageHeadingRoute: ComponentsPageHeadingRoute,
  ComponentsRadioGroupRoute: ComponentsRadioGroupRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSidebarRoute: ComponentsSidebarRoute,
  ComponentsTextareaRoute: ComponentsTextareaRoute,
  ComponentsToggleRoute: ComponentsToggleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
