/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtomsInputRouteImport } from './routes/atoms/input'
import { Route as AtomsButtonRouteImport } from './routes/atoms/button'
import { Route as AtomsBadgeRouteImport } from './routes/atoms/badge'
import { Route as FragmentsSidebarIndexRouteImport } from './routes/fragments/sidebar/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomsInputRoute = AtomsInputRouteImport.update({
  id: '/atoms/input',
  path: '/atoms/input',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomsButtonRoute = AtomsButtonRouteImport.update({
  id: '/atoms/button',
  path: '/atoms/button',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomsBadgeRoute = AtomsBadgeRouteImport.update({
  id: '/atoms/badge',
  path: '/atoms/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const FragmentsSidebarIndexRoute = FragmentsSidebarIndexRouteImport.update({
  id: '/fragments/sidebar/',
  path: '/fragments/sidebar/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atoms/badge': typeof AtomsBadgeRoute
  '/atoms/button': typeof AtomsButtonRoute
  '/atoms/input': typeof AtomsInputRoute
  '/fragments/sidebar/': typeof FragmentsSidebarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atoms/badge': typeof AtomsBadgeRoute
  '/atoms/button': typeof AtomsButtonRoute
  '/atoms/input': typeof AtomsInputRoute
  '/fragments/sidebar': typeof FragmentsSidebarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atoms/badge': typeof AtomsBadgeRoute
  '/atoms/button': typeof AtomsButtonRoute
  '/atoms/input': typeof AtomsInputRoute
  '/fragments/sidebar/': typeof FragmentsSidebarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atoms/badge'
    | '/atoms/button'
    | '/atoms/input'
    | '/fragments/sidebar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atoms/badge'
    | '/atoms/button'
    | '/atoms/input'
    | '/fragments/sidebar'
  id:
    | '__root__'
    | '/'
    | '/atoms/badge'
    | '/atoms/button'
    | '/atoms/input'
    | '/fragments/sidebar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtomsBadgeRoute: typeof AtomsBadgeRoute
  AtomsButtonRoute: typeof AtomsButtonRoute
  AtomsInputRoute: typeof AtomsInputRoute
  FragmentsSidebarIndexRoute: typeof FragmentsSidebarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atoms/input': {
      id: '/atoms/input'
      path: '/atoms/input'
      fullPath: '/atoms/input'
      preLoaderRoute: typeof AtomsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atoms/button': {
      id: '/atoms/button'
      path: '/atoms/button'
      fullPath: '/atoms/button'
      preLoaderRoute: typeof AtomsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atoms/badge': {
      id: '/atoms/badge'
      path: '/atoms/badge'
      fullPath: '/atoms/badge'
      preLoaderRoute: typeof AtomsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragments/sidebar/': {
      id: '/fragments/sidebar/'
      path: '/fragments/sidebar'
      fullPath: '/fragments/sidebar/'
      preLoaderRoute: typeof FragmentsSidebarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtomsBadgeRoute: AtomsBadgeRoute,
  AtomsButtonRoute: AtomsButtonRoute,
  AtomsInputRoute: AtomsInputRoute,
  FragmentsSidebarIndexRoute: FragmentsSidebarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
