name: swift-ci

on:
  push:
    branches:
      - master
    paths:
      - 'swift/**'
      - '.github/workflows/swift-ci.yml'
  pull_request:
    paths:
      - 'swift/**'
      - '.github/workflows/swift-ci.yml'

jobs:
  linux-build-libs-1:
    needs: files-changed
    if: needs.files-changed.outputs.libs == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/gertrude-app/api-ci-build:6.2.1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-duet
        run: cd swift/duet && swift build
      - name: build-pairql
        run: cd swift/pairql && swift build
      - name: build-pairql-macapp
        run: cd swift/pairql-macapp && swift build

  linux-build-libs-2:
    needs: files-changed
    if: needs.files-changed.outputs.libs == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/gertrude-app/api-ci-build:6.2.1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-gertie
        run: cd swift/gertie && swift build
      - name: build-ts-interop
        run: cd swift/ts-interop && swift build
      - name: build-x-expect
        run: cd swift/x-expect && swift build
      - name: build-x-http
        run: cd swift/x-http && swift build
      - name: build-x-kit
        run: cd swift/x-kit && swift build
      - name: build-x-postmark
        run: cd swift/x-postmark && swift build
      - name: build-x-slack
        run: cd swift/x-slack && swift build
      - name: build-x-stripe
        run: cd swift/x-stripe && swift build

  linux-lib-test-libs-1:
    needs: files-changed
    if: needs.files-changed.outputs.libs == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/gertrude-app/api-ci-build:6.2.1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test-duet
        run: cd swift/duet && swift test
      - name: test-pairql-macapp
        run: cd swift/pairql-macapp && swift test

  linux-lib-test-libs-2:
    needs: files-changed
    if: needs.files-changed.outputs.libs == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/gertrude-app/api-ci-build:6.2.1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test-ts-interop
        run: cd swift/ts-interop && swift test
      - name: test-gertie
        run: cd swift/gertie && swift test
      - name: test-x-http
        run: cd swift/x-http && swift test
      - name: test-x-kit
        run: cd swift/x-kit && swift test
      - name: test-x-slack
        run: cd swift/x-slack && swift test

  linux-api-build:
    needs: files-changed
    if: needs.files-changed.outputs.api == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/gertrude-app/api-ci-build:6.2.1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: swift/api/.build
          key: api-build-v3-${{ hashFiles('swift/api/Package.resolved') }}
          restore-keys: api-build-v3-
      - name: meta
        id: meta
        uses: friends-library/dev/actions/ts-pack/actions/meta@master
        with:
          github_token: ${{ github.token }}
      - name: set-env-vars
        run: |
          DATESTR=$(TZ=America/New_York date +'%Y.%m.%d_%H.%M')
          SHORTSHA=${{ steps.meta.outputs.latest_commit_sha_short }}
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            API_ENV=production
            echo "SRCDIR=swift/api/.build/release" >> $GITHUB_ENV
            echo "DESTDIR=builds/production" >> $GITHUB_ENV
            echo "CONFIGURATION=release"     >> $GITHUB_ENV
          else
            API_ENV=staging
            echo "SRCDIR=swift/api/.build/debug"   >> $GITHUB_ENV
            echo "DESTDIR=builds/staging"    >> $GITHUB_ENV
            echo "CONFIGURATION=debug"       >> $GITHUB_ENV
          fi
          echo "FILENAME=api_${API_ENV}_${DATESTR}_${SHORTSHA}" >> $GITHUB_ENV
      - name: build-api
        run: |
          cd swift/api
          swift build -c $CONFIGURATION -Xswiftc -static-stdlib
          BIN_PATH=$(swift build -c $CONFIGURATION -Xswiftc -static-stdlib --show-bin-path)
          cp "${BIN_PATH}/Run" ../../${FILENAME}
      - name: scp-bin
        uses: appleboy/scp-action@v0.1.7
        with:
          host: api.gertrude.app
          username: ${{ secrets.API_SERVER_SSH_USER }}
          key: ${{ secrets.API_SERVER_SSH_KEY }}
          source: '${{ env.FILENAME }}'
          target: '${{ env.DESTDIR }}'
      - name: ssh-tasks
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: api.gertrude.app
          username: ${{ secrets.API_SERVER_SSH_USER }}
          key: ${{ secrets.API_SERVER_SSH_KEY }}
          envs: DESTDIR,FILENAME
          script: |
            ln -sf "./${FILENAME}" "${DESTDIR}/latest"
            chmod +x "${DESTDIR}/${FILENAME}" "${DESTDIR}/latest"
            cd ~/builds/production && ls -r api_* | grep -v $(basename $(readlink -f current)) | tail -n +11 | xargs rm
            cd ~/builds/staging && ls -r api_* | tail -n  +6 | xargs rm
            pm2 reset staging > /dev/null
            pm2 stop staging > /dev/null
            pm2 start staging > /dev/null
      - name: slack api prod deploy
        if: github.event_name != 'pull_request'
        env:
          PR_NUMBER: ${{ steps.meta.outputs.pull_request_number }}
          PR_TITLE: ${{ steps.meta.outputs.pull_request_title }}
        run: |
          apt-get update && apt-get install -y curl jq
          if [ -n "$PR_NUMBER" ] && [ -n "$PR_TITLE" ]; then
            PR_LINK="<https://github.com/gertrude-app/gertrude/pull/${PR_NUMBER}|${PR_TITLE}>"
            MESSAGE="Gertrude api *DEPLOY READY* ${PR_LINK}"
          else
            MESSAGE="Gertrude api *DEPLOY READY*"
          fi
          PAYLOAD=$(jq -n --arg text "$MESSAGE" '{
            channel: "C08GLK13HAB",
            text: $text,
            username: "Gertrude Bot",
            icon_emoji: ":robot_face:"
          }')
          curl -X POST \
            -H "Content-type: application/json; charset=utf-8" \
            -H "Authorization: Bearer $SLACK_API_TOKEN" \
            -d "$PAYLOAD" \
            https://slack.com/api/chat.postMessage

  linux-api-test:
    needs: files-changed
    if: needs.files-changed.outputs.api == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/gertrude-app/api-ci-build:6.2.1
    env:
      DATABASE_HOST: postgres
      AUTO_INCLUDED_KEYCHAIN_ID: 77777777-7777-7777-7777-777777777777
      SLACK_API_TOKEN: not-real
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_PASSWORD: vapor_password
          POSTGRES_DB: vapor_database
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: swift/api/.build
          key: api-test-v3-${{ hashFiles('swift/api/Package.resolved') }}
          restore-keys: api-test-v3-
      - name: test-api
        run: cd swift/api && swift test

  macapp-lib:
    needs: files-changed
    if: needs.files-changed.outputs.macapp == 'true'
    runs-on: macos-15
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 26.1.1
      - uses: actions/cache@v4
        with:
          path: swift/macapp/App/.build
          key: macapp-xc26.1.1--${{ hashFiles('swift/macapp/App/Package.resolved') }}
          restore-keys: macapp-xc26.1.1--
      - name: build
        run: cd swift/macapp/App && swift build
      - name: test
        run: cd swift/macapp/App && swift test

  macapp-build:
    needs: files-changed
    if: needs.files-changed.outputs.macapp == 'true' && github.event_name == 'pull_request'
    runs-on: macos-15
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 26.1.1
      - name: build
        run: |
          cd swift/macapp/Xcode
          xcodebuild -project Gertrude.xcodeproj -scheme Gertrude \
            -skipMacroValidation -destination 'generic/platform=macOS' \
            CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build

  iosapp-lib:
    needs: files-changed
    if: needs.files-changed.outputs.iosapp == 'true'
    runs-on: macos-15
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 26.1.1
      - uses: actions/cache@v4
        with:
          path: swift/iosapp/lib-ios/.build
          key: iosapp-xc26.1.1--${{ hashFiles('swift/iosapp/lib-ios/Package.resolved') }}
          restore-keys: iosapp-xc26.1.1--
      - name: build
        run: cd swift/iosapp/lib-ios && swift build
      - name: test
        run: cd swift/iosapp/lib-ios && swift test

  iosapp-build:
    needs: files-changed
    if: needs.files-changed.outputs.iosapp == 'true' && github.event_name == 'pull_request'
    runs-on: macos-15
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 26.1.1
      - name: build
        run: |
          cd swift/iosapp
          touch config/Local.xcconfig
          xcodebuild -project Gertrude-iOS.xcodeproj -scheme Gertrude-iOS \
            -skipMacroValidation -destination 'generic/platform=iOS Simulator' build

  podcasts-lib:
    needs: files-changed
    if: needs.files-changed.outputs.podcasts == 'true' && github.event_name == 'pull_request'
    runs-on: macos-15
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 26.1.1
      - uses: actions/cache@v4
        with:
          path: |
            swift/podcasts/lib-tca/.build
            swift/podcasts/lib-core/.build
            swift/podcasts/lib-views/.build
          key: podcasts-xc26.1.1-${{ hashFiles('swift/podcasts/lib-tca/Package.resolved', 'swift/podcasts/lib-core/Package.resolved', 'swift/podcasts/lib-views/Package.resolved') }}
          restore-keys: podcasts-xc26.1.1-
      - name: setup just
        uses: extractions/setup-just@v2
      - name: build
        run: cd swift/podcasts && just build
      - name: test
        run: cd swift/podcasts && just test

  swift-lint:
    needs: files-changed
    if: needs.files-changed.outputs.swift == 'true' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container: ghcr.io/gertrude-app/api-ci-build:6.2.1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          git clone --depth 1 --branch 0.58.5 https://github.com/nicklockwood/SwiftFormat
          cd SwiftFormat && swift build -c debug
          cp ./.build/debug/swiftformat /usr/local/bin
          cd ../ && rm -rf SwiftFormat/
      - name: swiftlint
        run: cd swift && /usr/local/bin/swiftformat . --lint


  xml-lint:
    needs: files-changed
    if: needs.files-changed.outputs.swift == 'true' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup just
        uses: extractions/setup-just@v2
      - name: install
        run: cargo install xml-lint
      - name: xml-lint
        run: cd swift && just lint-xml

  files-changed:
    runs-on: ubuntu-latest
    outputs:
      macapp: ${{ steps.changes.outputs.macapp }}
      iosapp: ${{ steps.changes.outputs.iosapp }}
      podcasts: ${{ steps.changes.outputs.podcasts }}
      libs: ${{ steps.changes.outputs.libs }}
      api: ${{ steps.changes.outputs.api }}
      swift: ${{ steps.changes.outputs.swift }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            macapp:
              - swift/macapp/**
              - swift/pairql-macapp/**
              - swift/pairql/**
              - swift/gertie/**
              - swift/x-kit/**
              - swift/ts-interop/**
            iosapp:
              - swift/iosapp/**
              - swift/pairql-iosapp/**
              - swift/pairql/**
              - swift/gertie/**
              - swift/x-kit/**
            podcasts:
              - swift/podcasts/**
              - swift/pairql/**
              - swift/pairql-podcasts/**
              - swift/api/Sources/Api/PairQL/Podcast/**
            libs:
              - swift/duet/**
              - swift/pairql/**
              - swift/pairql-macapp/**
              - swift/gertie/**
              - swift/ts-interop/**
              - swift/x-expect/**
              - swift/x-http/**
              - swift/x-kit/**
              - swift/x-postmark/**
              - swift/x-slack/**
              - swift/x-stripe/**
              - swift/x-aws/**
            api:
              - swift/api/**
              - swift/duet/**
              - swift/pairql/**
              - swift/pairql-macapp/**
              - swift/pairql-iosapp/**
              - swift/pairql-podcasts/**
              - swift/gertie/**
              - swift/ts-interop/**
              - swift/x-expect/**
              - swift/x-http/**
              - swift/x-kit/**
              - swift/x-postmark/**
              - swift/x-slack/**
              - swift/x-stripe/**
              - swift/x-aws/**
            swift:
              - swift/**

env:
  DATABASE_NAME: vapor_database
  DATABASE_USERNAME: vapor_username
  DATABASE_PASSWORD: vapor_password
  TEST_DATABASE_NAME: vapor_database
  CLOUD_STORAGE_KEY: not-real
  CLOUD_STORAGE_SECRET: not-real
  CLOUD_STORAGE_ENDPOINT: not-real
  CLOUD_STORAGE_BUCKET: not-real
  CLOUD_STORAGE_BUCKET_URL: /not-real
  CLOUDFLARE_SECRET: not-real
  TWILIO_ACCOUNT_SID: not-real
  TWILIO_AUTH_TOKEN: not-real
  TWILIO_FROM_PHONE_US: not-real
  TWILIO_FROM_PHONE_UK: not-real
  DASHBOARD_URL: /dashboard
  POSTMARK_API_KEY: not-real
  POSTMARK_SERVER_ID: 12345
  PRIMARY_SUPPORT_EMAIL: not-real
  SUPER_ADMIN_EMAIL: not-real
  STRIPE_SUBSCRIPTION_PRICE_ID: not-real
  STRIPE_SECRET_KEY: not-real
  SWIFT_DETERMINISTIC_HASHING: 1
  TASK_MEGA_YIELD_COUNT: 250
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  APPSTORE_ISSUER_ID: not-real
  APPSTORE_KEY_ID: not-real
  APPSTORE_PRIVATE_KEY: not-real

