name: web-ci

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - 'swift/api/Sources/Api/PairQL/Dashboard/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    types: [opened, synchronize, labeled]
    paths:
      - 'web/**'
      - 'swift/api/Sources/Api/PairQL/Dashboard/**'
      - '.github/workflows/web-ci.yml'

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: install deps
        run: cd web && pnpm install
      - name: setup just
        uses: extractions/setup-just@v2
      - name: lint
        run: cd web && just lint
      - name: format
        run: cd web && just format-check
      - name: typecheck
        run: cd web && just typecheck
      - name: test
        run: cd web && just test

  storybook:
    name: storybook
    needs: files-changed
    if: needs.files-changed.outputs.storybook == 'true'
    runs-on: ubuntu-latest
    env:
      ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: install deps
        run: cd web && pnpm install
      - name: setup just
        uses: extractions/setup-just@v2
      - name: build storybook
        run: cd web && STORYBOOK_SCREENSHOT_TESTING=true just build-storybook
      - name: serve storybook
        run: |
          cd web
          mv -f storybook/storybook-static/{iframe,index}.html
          pnpm dlx serve@14.2.1 -l 4777 storybook/storybook-static &
      - name: screenshots
        run: |
          cd web
          just visual-test
          pnpm dlx @argos-ci/cli upload storybook/visual-tests/screenshots/argos || true
      - name: create screenshots pr
        id: pr
        uses: peter-evans/create-pull-request@v6
        if: github.event_name == 'pull_request'
        with:
          base: ${{ github.head_ref }}
          commit-message: '[automated] update screenshots from CI'
          branch: screenshots/patch/${{ github.head_ref }}
          delete-branch: true
          title: update screenshots from CI
      - name: pr comment
        if: ${{ steps.pr.outputs.pull-request-number }}
        uses: mshick/add-pr-comment@v2
        with:
          message: 'PR for changed screenshots: ${{ steps.pr.outputs.pull-request-url }}'

  dashboard:
    name: dashboard
    needs: files-changed
    if: github.event_name == 'pull_request' && needs.files-changed.outputs.dashboard == 'true'
    runs-on: ubuntu-latest
    env:
      VITE_API_ENDPOINT: ${{ secrets.STAGING_API_ENDPOINT }}
      VITE_TEST_ADMIN_CREDS: ${{ secrets.TEST_ADMIN_CREDS }}
      VITE_TURNSTILE_SITEKEY: ${{ secrets.DASH_TURNSTILE_SITEKEY }}
    steps:
      - name: reset staging
        run: curl --silent ${{ secrets.STAGING_API_RESET_ROUTE  }}; true
      - name: checkout
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: install deps
        run: cd web && pnpm install
      - name: setup just
        uses: extractions/setup-just@v2
      - name: build dashboard
        run: cd web && just build-dash
      - name: cypress
        uses: cypress-io/github-action@v6.6.0
        with:
          start: pnpm --filter @dash/app preview
          project: dash/app
          working-directory: web
      - name: upload-videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: web/dash/app/cypress/videos

  files-changed:
    runs-on: ubuntu-latest
    outputs:
      admin: ${{ steps.changes.outputs.admin }}
      appviews: ${{ steps.changes.outputs.appviews }}
      dashboard: ${{ steps.changes.outputs.dashboard }}
      site: ${{ steps.changes.outputs.site }}
      storybook: ${{ steps.changes.outputs.storybook }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            admin:
              - web/admin/**
              - web/dash/ambient/**
              - web/shared/**
            appviews:
              - web/appviews/**
            dashboard:
              - web/dash/**
              - web/shared/**
              - swift/api/Sources/Api/PairQL/Dashboard/**
            site:
              - web/site/**
              - web/shared/**
            storybook:
              - web/storybook/**
              - web/appviews/**
              - web/supervise/**
              - web/site/**
              - web/shared/**
              - web/dash/ambient/**
              - web/dash/block-rules/**
              - web/dash/components/**
              - web/dash/datetime/**
              - web/dash/keys/**
              - web/dash/types/**
              - web/dash/utils/**

  appviews-comment:
    needs: files-changed
    if: github.event_name == 'pull_request' && needs.files-changed.outputs.appviews == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: pr comment
        uses: mshick/add-pr-comment@v2
        with:
          message-id: appview-reminder
          message: |
            ### ⚠️ **Warning: `appviews/` dir modified** ⚠️
            Beware of regressions in older macOS versions involving:
            1. **Focusable elements**: All focusable elements (form elements, buttons, links, etc.) must have `tabIndex="-1"` to prevent layout shift issues.
            2. **`gap-*` utilities** are not supported in Catalina

  site:
    name: site
    needs: files-changed
    if: github.event_name == 'pull_request' && needs.files-changed.outputs.site == 'true'
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_FORMS_ENDPOINT: /not-real
      NEXT_PUBLIC_TURNSTILE_SITEKEY: not-real
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: install deps
        run: cd web && pnpm install
      - name: setup just
        uses: extractions/setup-just@v2
      - name: build site
        run: cd web && just build-site

  admin:
    name: admin
    needs: files-changed
    if: github.event_name == 'pull_request' && needs.files-changed.outputs.admin == 'true'
    runs-on: ubuntu-latest
    env:
      VITE_API_ENDPOINT: /not-real
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: install deps
        run: cd web && pnpm install
      - name: setup just
        uses: extractions/setup-just@v2
      - name: build admin
        run: cd web && just build-admin
