packages:
  - appviews
  - dash/*
  - site
  - shared/*
  - storybook
  - smoke
  - admin
  - supervise
  - ui
  - new-dashbaord

onlyBuiltDependencies:
  - core-js-pure
  - cypress
  - esbuild
  - lightningcss
  - nx
  - puppeteer
  - sharp
