packages:
  - account
  - appviews
  - dash/*
  - site
  - shared/*
  - storybook
  - storybook-v2
  - smoke
  - admin
  - supervise
  - ui

onlyBuiltDependencies:
  - core-js-pure
  - cypress
  - esbuild
  - lightningcss
  - nx
  - puppeteer
  - sharp
